# index:
#     path: /
#     controller: App\Controller\DefaultController::index

# rdmBackground:
#     path: /rdmBackground
#     controller: App\Controller\RandomColorController::generateBackground

# helloWorld:
#     path: /hello
#     controller: App\Controller\HelloController::hello